### ISSUE TITLE
Follow Error-First Callbacks standard

### ISSUE THREAD

**Issue by dotnetCarpenter** [hackerkid/node-github-notification#1]
Please follow the Error-First Callbacks standard as described here: http://thenodeway.io/posts/understanding-error-first-callbacks/?utm_source=fredkschott.com&utm_medium=referral

Nice little module :+1:

**Comment by hackerkid** [comment]
I am using `XMLHttpRequest` package for the module which handles the error automatically. But I would try to figure out a way to implement Error-First Callbacks by using a different package. Thanks for letting know. I am leaving the issue open.

**Comment by dotnetCarpenter** [comment]
You don't need to use a different package and I'm afraid that `XMLHttpRequest` does not handle errors for you.

What happens if
1. the connection is lost?
2. the server doesn't response?
3. the JSON is malformed?
These things can be tested
1. try to disconnect your pc while making a request
2. try writing a wrong URL to see what I mean
3. try to retreat a local JSON file that you deliberate made a mistake in

I'll send you a PR with the change.

**Comment by hackerkid** [comment]
Merged. Closing the issue. Thanks.
